// Generated by CoffeeScript 1.3.3
(function() {
  var Fetcher, endDate, fetcher, host, jquery, path, request, startDate, symbol;

  request = require('request');

  jquery = require('jquery');

  Fetcher = (function() {

    function Fetcher() {}

    Fetcher.prototype.buildQueryString = function(symbol, startDate, endDate) {
      var a, b, c, d, e, f, _ref, _ref1;
      _ref = [startDate.getMonth(), startDate.getDay(), startDate.getFullYear()], a = _ref[0], b = _ref[1], c = _ref[2];
      _ref1 = [endDate.getMonth(), endDate.getDay(), endDate.getFullYear()], d = _ref1[0], e = _ref1[1], f = _ref1[2];
      return {
        s: symbol,
        a: a,
        b: b,
        c: c,
        d: d,
        e: e,
        f: f,
        g: 'd',
        ignore: '.csv'
      };
    };

    return Fetcher;

  })();

  fetcher = new Fetcher();

  symbol = 'crm';

  startDate = new Date("2012/01/01");

  endDate = new Date;

  console.log(fetcher.buildQueryString(symbol, startDate, endDate));

  host = "http://ichart.finance.yahoo.com";

  path = "/table.csv";

}).call(this);
